const LIVE_VIDEO_TITLES = new Set([
  "盛れ!ミ・アモーレ",
  "四の五の言わず颯と別れてあげた",
  "GIRLS BE AMBITIOUS! 2026",
  "プラトニック・プラネット",
  "BLOODY BULLET",
  "私が言う前に抱きしめなきゃね",
  "甘えんな",
  "ひとりで生きられそうって それってねえ、褒めているの?",
  "Fiesta! Fiesta!",
  "CHOICE & CHANCE",
  "トウキョウ・ブラー",
  "イジワルしないで 抱きしめてよ",
  "素直に甘えて",
  "微炭酸",
  "ノクチルカ",
  "雨の中の口笛",
  "愛・愛・傘",
  "TOKYOグライダー",
  "伊達じゃないよ うちの人生は",
  "プライド・ブライト",
  "Va-Va-Voom",
  "この世界は捨てたもんじゃない",
  "Goal〜明日はあっちだよ〜",
  "ナイモノラブ",
  "Never Never Surrender",
  "今夜はHearty Party",
  "G.O.A.T.",
  "次々続々",
  "マナーモード",
  "Celebrate! Celebrate!",
  "BaBaBa Burning Love！",
  "トラブルメーカー",
  "右ななめ後ろから",
  "プリズンブレイカー",
  "もう一歩",
  "臥薪嘗胆",
  "FAST PASS",
  "限りあるMoment",
  "光のうた",
  "ライアーライナー",
  "ちはやぶる",
  "今日を胸に飾って",
  "Go Your Way",
  "ラヴィ・ダヴィ",
  "なんだかんだエヴリデー！",
  "黙ってついてこい！",
  "わかってるっつーの！",
  "女の愛想は武器じゃない",
  "想定内！",
  "ポジティブプログラム",
]);

export const hasLiveVideoSource = (title: string): boolean =>
  LIVE_VIDEO_TITLES.has(title);
