export type SetlistTrackSource = "ライブ映像あり" | "YouTube Music" | "音源未設定";

export type SetlistTrack = {
  title: string;
  source: SetlistTrackSource;
  videoId?: string;
  note?: string;
  kind?: "song" | "note";
};

export type LiveSetlist = {
  id: string;
  title: string;
  note: string;
  date?: string;
  sortDate?: string;
  venue?: string;
  sourceUrl?: string;
  sourceLabel?: string;
  tracks: SetlistTrack[];
};

const song = (
  title: string,
  note?: string,
  kind: SetlistTrack["kind"] = "song"
): SetlistTrack => ({
  title,
  source: "音源未設定",
  kind,
  ...(note ? { note } : {}),
});

export const liveSetlists: LiveSetlist[] = [
  {
    id: "up-to-11-2026",
    title: "Juice=Juice LIVE TOUR 2026 UP TO 11",
    note: "2026年春ライブツアーの基本セトリです。2026年4月18日 Zepp Namba(OSAKA) 1公演目の参戦記録を元に登録しています。",
    date: "2026.04.17 - 2026.05.27",
    sortDate: "2026.05.27",
    venue: "ツアー各会場",
    sourceUrl: "https://note.com/tsunechan0707/n/ne198dcf909c1",
    sourceLabel: "参戦記録を開く",
    tracks: [
      { title: "BLOODY BULLET", source: "音源未設定" },
      {
        title: "ひとりで生きられそうって それってねえ、褒めているの?",
        source: "音源未設定",
      },
      { title: "CHOICE & CHANCE", source: "ライブ映像あり", videoId: "a1MDCj0T0c4" },
      { title: "GIRLS BE AMBITIOUS! 2026", source: "音源未設定" },
      { title: "好きって言ってよ", source: "音源未設定" },
      { title: "四の五の言わず颯と別れてあげた", source: "音源未設定" },
      { title: "トウキョウ・ブラー", source: "ライブ映像あり", videoId: "1blvz_OhPSI" },
      { title: "Never Never Surrender", source: "音源未設定" },
      {
        title: "私が言う前に抱きしめなきゃね",
        source: "音源未設定",
        note: "ここからの3曲は公演内でメンバーをリレーする構成。",
      },
      { title: "イジワルしないで 抱きしめてよ", source: "音源未設定" },
      { title: "ロマンスの途中", source: "音源未設定" },
      { title: "禁断少女", source: "音源未設定" },
      { title: "Fiesta! Fiesta!", source: "音源未設定" },
      { title: "甘えんな", source: "音源未設定" },
      { title: "ナイモノラブ", source: "音源未設定" },
      { title: "プラトニック・プラネット", source: "音源未設定" },
      { title: "プライド・ブライト", source: "音源未設定" },
      { title: "盛れ!ミ・アモーレ", source: "音源未設定" },
      { title: "Magic of Love", source: "音源未設定" },
      { title: "未来へ、さあ走り出せ!", source: "音源未設定" },
    ],
  },
  {
    id: "triangrooove2-special-2024",
    title: "Juice=Juice Concert Tour 2024 TRIANGROOOVE2 Special",
    note: "2024年11月19日 日本武道館公演のセトリです。",
    date: "2024.11.19",
    sortDate: "2024.11.19",
    venue: "日本武道館",
    sourceUrl: "https://orekoko.site/231/",
    sourceLabel: "出典を開く",
    tracks: [
      { title: "トウキョウ・ブラー", source: "ライブ映像あり", videoId: "1blvz_OhPSI" },
      { title: "プラトニック・プラネット", source: "音源未設定" },
      { title: "今夜はHearty Party", source: "音源未設定" },
      { title: "POPPIN’ LOVE", source: "音源未設定" },
      { title: "禁断少女", source: "音源未設定" },
      { title: "イニミニマニモ〜恋のライバル宣言〜", source: "音源未設定" },
      { title: "ライバル", source: "音源未設定" },
      { title: "地団駄ダンス", source: "音源未設定" },
      { title: "ポップミュージック", source: "音源未設定" },
      { title: "あばれてっか?! ハヴアグッタイ", source: "音源未設定" },
      { title: "This is 運命", source: "音源未設定" },
      { title: "ノクチルカ", source: "音源未設定" },
      { title: "全部賭けてGO!!", source: "音源未設定" },
      { title: "Va-Va-Voom", source: "音源未設定" },
      { title: "情熱エクスタシー", source: "音源未設定" },
      { title: "Future Smile", source: "音源未設定" },
      { title: "Never Never Surrender", source: "音源未設定" },
      { title: "STAGE〜アガッてみな〜", source: "音源未設定" },
      { title: "ナイモノラブ", source: "音源未設定" },
      { title: "GIRLS BE AMBITIOUS!", source: "音源未設定" },
      { title: "プライド・ブライト", source: "音源未設定" },
      { title: "Fiesta! Fiesta!", source: "音源未設定" },
      { title: "がんばれないよ", source: "音源未設定" },
      { title: "この世界は捨てたもんじゃない", source: "音源未設定" },
      { title: "Goal〜明日はあっちだよ〜", source: "音源未設定" },
    ],
  },
  {
    id: "crimson-azure-special-2025",
    title: "Juice=Juice Concert Tour 2025 Crimson×Azure Special",
    note: "2025年6月23日 日本武道館公演のセトリです。",
    date: "2025.06.23",
    sortDate: "2025.06.23",
    venue: "日本武道館",
    sourceUrl: "https://orekoko.site/860/",
    sourceLabel: "出典を開く",
    tracks: [
      { title: "あばれてっか?! ハヴアグッタイ", source: "音源未設定" },
      { title: "Va-Va-Voom", source: "音源未設定" },
      { title: "ナイモノラブ", source: "音源未設定" },
      { title: "初恋の亡霊", source: "音源未設定" },
      { title: "風に吹かれて", source: "音源未設定" },
      {
        title: "ひとりで生きられそうって それってねえ、褒めているの?",
        source: "音源未設定",
      },
      { title: "DOWN TOWN", source: "音源未設定" },
      { title: "Vivid Midnight", source: "音源未設定" },
      { title: "プラトニック・プラネット", source: "音源未設定" },
      { title: "雨の中の口笛", source: "音源未設定" },
      { title: "Mon Amour", source: "音源未設定" },
      { title: "大人の事情", source: "音源未設定" },
      { title: "Next is you!", source: "音源未設定" },
      { title: "選ばれし私達", source: "音源未設定" },
      { title: "明日やろうはバカやろう", source: "音源未設定" },
      { title: "トウキョウ・ブラー", source: "ライブ映像あり", videoId: "1blvz_OhPSI" },
      { title: "五月雨美女がさ乱れる", source: "音源未設定" },
      { title: "CHOICE & CHANCE", source: "ライブ映像あり", videoId: "a1MDCj0T0c4" },
      { title: "プライド・ブライト", source: "音源未設定" },
      { title: "GIRLS BE AMBITIOUS!", source: "音源未設定" },
      { title: "Fiesta! Fiesta!", source: "音源未設定" },
      { title: "Magic of Love", source: "音源未設定" },
      { title: "生まれたてのBaby Love", source: "音源未設定" },
      { title: "如雨露", source: "音源未設定" },
      { title: "G.O.A.T.", source: "音源未設定" },
    ],
  },
  {
    id: "queen-of-hearts-2025",
    title: "Juice=Juice LIVE TOUR 2025 Queen of Hearts",
    note: "2025年秋ライブツアーの基本セトリです。Queenソロパフォーマンス枠は公演ごとに曲が変わります。",
    date: "2025.09.17 - 2025.11.08",
    sortDate: "2025.11.08",
    venue: "ツアー各会場",
    sourceUrl: "https://orekoko.site/1150/",
    sourceLabel: "出典を開く",
    tracks: [
      { title: "盛れ!ミ・アモーレ", source: "音源未設定" },
      { title: "ナイモノラブ", source: "音源未設定" },
      { title: "STAGE〜アガッてみな〜", source: "音源未設定" },
      { title: "素直に甘えて", source: "音源未設定" },
      { title: "イジワルしないで 抱きしめてよ", source: "音源未設定" },
      { title: "私が言う前に抱きしめなきゃね", source: "音源未設定" },
      { title: "四の五の言わず颯と別れてあげた", source: "音源未設定" },
      { title: "トウキョウ・ブラー", source: "ライブ映像あり", videoId: "1blvz_OhPSI" },
      { title: "プライド・ブライト", source: "音源未設定" },
      {
        title: "ひとりで生きられそうって それってねえ、褒めているの?",
        source: "音源未設定",
      },
      { title: "Va-Va-Voom", source: "音源未設定" },
      {
        title: "Queenソロパフォーマンス",
        source: "音源未設定",
        kind: "note",
        note: "公演ごとに差し替え。例: カラダだけが大人になったんじゃない / 好きって言ってよ / TOKYOグライダー / 甘えんな など",
      },
      { title: "BLOODY BULLET", source: "音源未設定" },
      { title: "プラトニック・プラネット", source: "音源未設定" },
      { title: "全部賭けてGO!!", source: "音源未設定" },
      { title: "あばれてっか?! ハヴアグッタイ", source: "音源未設定" },
      { title: "明日やろうはバカやろう", source: "音源未設定" },
      { title: "CHOICE & CHANCE", source: "ライブ映像あり", videoId: "a1MDCj0T0c4" },
      { title: "Goal〜明日はあっちだよ〜", source: "音源未設定" },
      { title: "KEEP ON 上昇志向!!", source: "音源未設定" },
    ],
  },
  {
    id: "juice-juice-day-2025-special-live",
    title: "スペシャルライブ2025 ～10月10日はJuice=Juiceの日～",
    note: "YouTube Musicのライブ音源プレイリストを元にしたコール練習用セトリです。",
    date: "2025.10.10",
    sortDate: "2025.10.10",
    venue: "ライブ音源",
    sourceUrl:
      "https://music.youtube.com/playlist?list=OLAK5uy_kyCqrDNJoYCDEqGeM3G4bSMBbV6JN8HrI",
    sourceLabel: "YouTube Musicで開く",
    tracks: [
      {
        title: "四の五の言わず颯と別れてあげた",
        source: "YouTube Music",
        videoId: "x6IpZQmiUl0",
      },
      {
        title: "ひとりで生きられそうって それってねえ、褒めているの?",
        source: "YouTube Music",
        videoId: "-l3hTH4M7EQ",
      },
      {
        title: "イジワルしないで 抱きしめてよ",
        source: "YouTube Music",
        videoId: "sVNsd-Wn_UU",
      },
      {
        title: "素直に甘えて",
        source: "YouTube Music",
        videoId: "NsfJvn7-aDM",
      },
      { title: "微炭酸", source: "ライブ映像あり", videoId: "v4JVTZ3kK-Y" },
      { title: "ノクチルカ", source: "YouTube Music", videoId: "uSKuScmtrfE" },
      {
        title: "雨の中の口笛",
        source: "YouTube Music",
        videoId: "ltsS3O29aM4",
      },
      { title: "愛・愛・傘", source: "YouTube Music", videoId: "6Y2X6RxYnYA" },
      {
        title: "TOKYOグライダー",
        source: "YouTube Music",
        videoId: "LZlLhbc-ARI",
      },
      {
        title: "伊達じゃないよ うちの人生は",
        source: "YouTube Music",
        videoId: "JQ270gg4PPM",
      },
      {
        title: "プライド・ブライト",
        source: "YouTube Music",
        videoId: "sjz8xSJdaUc",
      },
      { title: "Va-Va-Voom", source: "YouTube Music", videoId: "xdw3rkeSJlA" },
      {
        title: "盛れ!ミ・アモーレ",
        source: "YouTube Music",
        videoId: "dk_sbTrOvbw",
      },
      {
        title: "この世界は捨てたもんじゃない",
        source: "YouTube Music",
        videoId: "ku_JoTRHYpU",
      },
      {
        title: "Goal〜明日はあっちだよ〜",
        source: "YouTube Music",
        videoId: "QYiMYubszU8",
      },
    ],
  },
];

export const groupSetlists: Record<string, LiveSetlist[]> = {
  "juice-juice": liveSetlists,
  angerme: [
    {
      id: "in-to-you-2026-spring",
      title: "ANGERME 2026 Spring Tour 〜陰と陽〜",
      note: "2026年春ツアーの基本セトリです。メドレーと回替わり曲を含みます。",
      date: "2026.04.18 - 2026.06.23",
      sortDate: "2026.06.23",
      venue: "ツアー各会場 / 日本武道館",
      sourceUrl:
        "https://helloproject.fandom.com/wiki/ANGERME_2026_Spring_Tour_~In_to_You~",
      sourceLabel: "出典を開く",
      tracks: [
        song("プリズンブレイカー"),
        song("次々続々"),
        song("マナーモード"),
        song("愛されルート A or B？"),
        song("BaBaBa Burning Love！"),
        song("全然起き上がれないSUNDAY"),
        song("限りあるMoment"),
        song("愛さえあればなんにもいらない", "メドレー / In Team"),
        song("ミラー・ミラー", "メドレー / In Team"),
        song("泳げないMermaid", "メドレー / In Team"),
        song("カクゴして！", "メドレー / You Team"),
        song("上手く言えない", "メドレー / You Team"),
        song("悠々閑々 gonna be alright!!", "メドレー / You Team"),
        song("トラブルメーカー"),
        song("アイノケダモノ"),
        song("ライフ イズ ビューティフル！", "回替わり"),
        song("臥薪嘗胆", "回替わり"),
        song("人生、すなわちパンタ・レイ"),
        song("悔しいわ"),
        song("46億年LOVE"),
        song("THANK YOU, HELLO GOOD BYE"),
      ],
    },
    {
      id: "keep-your-smile-2025-autumn",
      title: "アンジュルム ライブツアー 2025秋 Keep Your Smile！",
      note: "2025年秋ライブツアーの基本セトリです。歌唱メンバー回替わりの曲を含みます。",
      date: "2025.09.06 - 2025.11.15",
      sortDate: "2025.11.15",
      venue: "ツアー各会場",
      sourceUrl: "https://orekoko.site/1105/",
      sourceLabel: "出典を開く",
      tracks: [
        song("愛すべきべき Human Life"),
        song("出すぎた杭は打たれない"),
        song("乙女の逆襲"),
        song("臥薪嘗胆"),
        song("FAST PASS"),
        song("明晩、ギャラクシー劇場で"),
        song("夢見る １５歳", "歌唱メンバー回替わり"),
        song("悠々閑々 gonna be alright!!"),
        song("有頂天LOVE"),
        song("ショートカット", "歌唱メンバー回替わり"),
        song("限りあるMoment"),
        song("私、ちょいとカワイイ裏番長"),
        song("マナーモード"),
        song("46億年LOVE"),
        song("大器晩成"),
        song("もう一歩"),
        song("スキちゃん"),
        song("友よ"),
      ],
    },
  ],
  "morning-musume": [
    {
      id: "rays-of-light-2026-spring",
      title: "モーニング娘。'26 コンサートツアー春 - Rays Of Light -",
      note: "2026年春ツアーの基本セトリです。メドレーと回替わり/コーナー曲を含みます。",
      date: "2026.04.11 - 2026.06.24",
      sortDate: "2026.06.24",
      venue: "ツアー各会場 / 日本武道館",
      sourceUrl:
        "https://helloproject.fandom.com/wiki/Morning_Musume_%2726_Concert_Tour_Haru_-_Rays_Of_Light_-",
      sourceLabel: "出典を開く",
      tracks: [
        song("THE マンパワー！！！"),
        song("One・Two・Three(23 Ver.)"),
        song("泡沫サタデーナイト！"),
        song("なんちゃって恋愛"),
        song("気まぐれプリンセス"),
        song("3、2、1 BREAKIN&#x27;OUT!"),
        song("Hey! Unfair Baby"),
        song("わがまま 気のまま 愛のジョーク"),
        song("ザ☆ピ〜ス！(23 Ver.)", "メドレー"),
        song("LOVEマシーン(updated 23 Ver.)", "メドレー"),
        song("そうだ！We&#x27;re ALIVE(updated 23 Ver.)", "メドレー"),
        song("恋愛レボリューション21(updated)", "メドレー"),
        song("Pattern Varies", "回替わり枠", "note"),
        song("ONLY ONE SONG Corner", "コーナー枠", "note"),
        song("雨の降らない星では愛せないだろう？"),
        song("Chu Chu Chu 僕らの未来", "メドレー"),
        song("よしよししてほしいの", "メドレー"),
        song("私のなんにもわかっちゃない", "メドレー"),
        song("勇敢なダンス", "メドレー"),
        song("Wake-up Call～目覚めるとき～", "メドレー"),
        song("What is LOVE？(23 Ver.)", "メドレー"),
        song("私のラミンタッチオーネ（Lamentazione）"),
        song("Are you Happy?"),
        song("てか HAPPYのHAPPY！"),
        song("明るく良い子"),
        song("この地球の平和を本気で願ってるんだよ！"),
        song("気になるその気の歌"),
      ],
    },
    {
      id: "movin-forward-2025-autumn",
      title: "モーニング娘。'25 コンサートツアー秋 ～Movin' Forward～",
      note: "2025年秋ツアーの基本セトリです。ユニット曲・メドレーを含みます。",
      date: "2025.09.13 - 2025.11.30",
      sortDate: "2025.11.30",
      venue: "ツアー各会場",
      sourceUrl: "https://orekoko.site/1121/",
      sourceLabel: "出典を開く",
      tracks: [
        song("ラヴ＆ピィ〜ス！HEROがやって来たっ。"),
        song("てか HAPPYのHAPPY！"),
        song("Happy birthday to Me!"),
        song("明るく良い子"),
        song("セクシーキャットの演説"),
        song("HEAVY GATE"),
        song("ロマンスに目覚める妄想女子の歌"),
        song("What is LOVE?"),
        song("シルバーの腕時計", "ユニット曲"),
        song("Give me 愛", "ユニット曲"),
        song("Take off is now!", "ユニット曲"),
        song("大きい瞳", "ユニット曲"),
        song("通学列車", "ユニット曲"),
        song("Rockの定義", "ユニット曲"),
        song("もう 我慢できないわ〜Love ice cream〜", "ユニット曲"),
        song("Only you", "ユニット曲"),
        song("幸せ指数 発表されたい", "ユニット曲"),
        song("ボン キュッ! ボン キュッ! BOMB GIRL", "ユニット曲"),
        song("時空を超え 宇宙を超え"),
        song("The 摩天楼ショー"),
        song("インスピレーション！"),
        song("What’s Up? 愛はどうなのよ～"),
        song("Go Girl 〜恋のヴィクトリー〜"),
        song("笑顔YESヌード", "メドレー"),
        song("女と男のララバイゲーム", "メドレー"),
        song("気まぐれプリンセス", "メドレー"),
        song("恋愛ハンター", "メドレー"),
        song("自由な国だから", "メドレー"),
        song("Teenage Solution", "メドレー"),
        song("I surrender 愛されど愛", "メドレー"),
        song("気になるその気の歌"),
        song("One・Two・Three"),
        song("恋愛Destiny～本音を論じたい～"),
        song("わがまま 気のまま 愛のジョーク"),
        song("友情〜心のブスにはならねぇ！〜"),
        song("シャボン玉"),
        song("青春小僧が泣いている"),
        song("BRAND NEW MORNING"),
        song("Be Alive"),
        song("涙ッチ"),
      ],
    },
  ],
  "ocha-norma": [
    {
      id: "overdrive-challenge-2026-spring",
      title: "OCHA NORMA LIVE TOUR 2026 SPRING ～Overdrive CHAllenge～",
      note: "2026年春ライブツアーの基本セトリです。回替わり曲を含みます。",
      date: "2026.04.11 - 2026.06.04",
      sortDate: "2026.06.04",
      venue: "ツアー各会場",
      sourceUrl:
        "https://helloproject.fandom.com/wiki/OCHA_NORMA_LIVE_TOUR_2026_SPRING_~Overdrive_CHAllenge~",
      sourceLabel: "出典を開く",
      tracks: [
        song("だんとつで愛して"),
        song("女の愛想は武器じゃない"),
        song("学校では教えてくれないこと"),
        song("運命 CHACHACHACHA～N"),
        song("シェケナーレ"),
        song("Hello! 生まれた意味がきっとある(OCHA NORMA Ver.)"),
        song("ちょっと情緒不安定？…夏", "回替わり"),
        song("恋のクラウチングスタート", "回替わり"),
        song("わかってるっつーの！", "回替わり"),
        song("お祭りデビューだぜ！", "回替わり"),
        song("今日を胸に飾って"),
        song("Liar Liner"),
        song("オチャノマ マホロバ イコイノバ～昭和も令和もワッチャワチャ～"),
        song("cha cha SING(2024 OCHA NORMA Ver.)"),
        song("ちはやぶる"),
        song("黙ってついてこい！"),
        song("想定内！"),
      ],
    },
    {
      id: "uchira-no-jimoto-2025-spring",
      title: "OCHA NORMA LIVE TOUR 2025 ウチらの地元は日本じゃん！",
      note: "2025年春ライブツアーの基本セトリです。カバー曲・ユニット曲を含みます。",
      date: "2025.03.23 - 2025.06.07",
      sortDate: "2025.06.07",
      venue: "ツアー各会場",
      sourceUrl: "https://orekoko.site/457/",
      sourceLabel: "出典を開く",
      tracks: [
        song("ウチらの地元は地球じゃん！"),
        song("ちはやぶる"),
        song("ラーメン大好き小泉さんの唄", "こぶしファクトリー曲"),
        song("Go Your Way"),
        song("ラヴィ・ダヴィ"),
        song("ウットーシー！"),
        song("SEXY SEXY", "Juice=Juice曲 / 斉藤"),
        song("シューティング スター", "スマイレージ曲 / 広本"),
        song("忘れらんない", "モーニング娘。曲 / 斉藤"),
        song("彼と一緒にお店がしたい", "モーニング娘。曲 / 北原"),
        song("恋はマグネット", "カントリー・ガールズ曲 / 中山"),
        song("幼なじみ", "藤本美貴曲 / 筒井"),
        song("記憶の迷路", "High-King曲 / 窪田"),
        song("DADDY! DADDY! DO!", "鈴木雅之 feat. 鈴木愛理曲 / 西﨑"),
        song("君の戦法", "℃-ute曲 / 米村・西﨑・北原・筒井"),
        song("AS FOR ONE DAY", "モーニング娘。曲 / 斉藤・広本・窪田・中山"),
        song("わかってるっつーの！"),
        song("懸命ブルース", "こぶしファクトリー曲"),
        song("Hello! 生まれた意味がきっとある"),
        song("シェケナーレ"),
        song("Good Luckの胸騒ぎ"),
        song("恋のクラウチングスタート"),
        song("なんだかんだエヴリデー！"),
      ],
    },
  ],
  "tsubaki-factory": [
    {
      id: "heat-it-up-2026-spring",
      title: "つばきファクトリー LIVE TOUR 2026 SPRING ～HEAT IT UP～",
      note: "2026年春ライブツアーのホール編セトリです。ユニット曲を含みます。",
      date: "2026.04.12 - 2026.05.29",
      sortDate: "2026.05.29",
      venue: "ツアー各会場",
      sourceUrl:
        "https://helloproject.fandom.com/wiki/Tsubaki_Factory_LIVE_TOUR_2026_SPRING_~HEAT_IT_UP~",
      sourceLabel: "出典を開く",
      tracks: [
        song("Power Flower ～今こそ一丸となれ～"),
        song("Stay free & Stay tuned"),
        song("最上級Story"),
        song("春恋歌"),
        song("まっぴらだってば！"),
        song("純愛クラッシャー"),
        song("FireWorks"),
        song("独り占め"),
        song("でも…いいよ"),
        song("月夜のパ・ド・ドゥ"),
        song("間違いじゃない 泣いたりしない"),
        song("約束・連絡・記念日", "ユニット曲"),
        song("Hair up 空へ！", "ユニット曲"),
        song("雨宿りのエピローグ", "ユニット曲"),
        song("愛は今、愛を求めてる", "ユニット曲"),
        song("だからなんなんだ！"),
        song("Just Try!"),
        song("アドレナリン・ダメ"),
        song("表面張力～Surface Tension～"),
        song("今夜だけ浮かれたかった"),
        song("大好きなのに、大好きだから"),
        song("スキップ・スキップ・スキップ"),
        song("勇気 It&#x27;s my Life！"),
      ],
    },
    {
      id: "our-days-budokan-2025",
      title: "つばきファクトリー 10th Anniversary Concert at BUDOKAN ～OUR DAYS～",
      note: "2025年4月30日 日本武道館公演のセトリです。メドレーを含みます。",
      date: "2025.04.30",
      sortDate: "2025.04.30",
      venue: "日本武道館",
      sourceUrl: "https://orekoko.site/537/",
      sourceLabel: "出典を開く",
      tracks: [
        song("今夜だけ浮かれたかった"),
        song("ハナモヨウ"),
        song("鼓動OK?"),
        song("笑って"),
        song("悲しみがとまらない"),
        song("間違いじゃない 泣いたりしない"),
        song("独り占め"),
        song("弱さじゃないよ、恋は"),
        song("月夜のパ・ド・ドゥ"),
        song("青春エクサバイト", "メドレー"),
        song("アイドル天職音頭", "メドレー"),
        song("I Need You 〜夜空の観覧車〜", "メドレー"),
        song("イマナンジ?", "メドレー"),
        song("春恋歌", "メドレー"),
        song("約束・連絡・記念日", "メドレー"),
        song("デートの日は二度くらいシャワーして出かけたい", "メドレー"),
        song("でも…いいよ", "メドレー"),
        song("ベイビースパイダー", "メドレー"),
        song("意識高い乙女のジレンマ", "メドレー"),
        song("抱きしめられてみたい", "メドレー"),
        song("ふわり、恋時計", "メドレー"),
        song("ガラクタDIAMOND", "メドレー"),
        song("涙のヒロイン降板劇", "メドレー"),
        song("私がオバさんになっても", "メドレー"),
        song("気高く咲き誇れ！", "メドレー"),
        song("青春まんまんなか！", "メドレー"),
        song("Just Try!", "メドレー"),
        song("低温火傷", "メドレー"),
        song("就活センセーション", "メドレー"),
        song("17才", "メドレー"),
        song("うるわしのカメリア"),
        song("Power Flower 〜今こそ一丸となれ〜"),
        song("君と僕の絆"),
        song("初恋サンライズ"),
        song("純情cm(センチメートル)"),
        song("三回目のデート神話"),
        song("アドレナリン・ダメ"),
        song("大好きなのに、大好きだから"),
        song("断捨ISM"),
        song("妄想だけならフリーダム"),
        song("My Darling 〜Do you love me?〜"),
        song("勇気 It’s my Life!"),
        song("スキップ・スキップ・スキップ"),
        song("My Days for You"),
      ],
    },
  ],
  "rosy-chronicle": [
    {
      id: "first-page-2025",
      title: "ロージークロニクル ファーストライブツアー2025 First Page!",
      note: "2025年ファーストライブツアーの基本セトリです。カバー曲を含みます。",
      date: "2025.11.02 - 2025.11.16",
      sortDate: "2025.11.16",
      venue: "ツアー各会場",
      sourceUrl: "https://orekoko.site/1431/",
      sourceLabel: "出典を開く",
      tracks: [
        song("へいらっしゃい！～ニッポンで会いましょう～"),
        song("夏のイナズマ"),
        song("CHOちょこっとロッケンロール"),
        song("ウブとズル"),
        song("女で地球は回ってる"),
        song("薔薇より美しい人生"),
        song("世の中薔薇色", "Berryz工房曲"),
        song("The 摩天楼ショー", "モーニング娘。曲"),
        song("原色GAL 派手に行くべ！", "後藤真希曲"),
        song("そう言えば", "松浦亜弥曲"),
        song("色とりどり伸びよ!!", "ハロプロ研修生曲"),
        song("8bit片想い"),
        song("ガオガオガオ"),
        song("ダイスキだけど付き合えない"),
        song("記念日未満"),
        song("未来ハジマリ"),
      ],
    },
  ],
};

export const getLiveSetlistsByLatest = (groupSlug = "juice-juice"): LiveSetlist[] =>
  (groupSetlists[groupSlug] ?? [])
    .slice()
    .sort((a, b) => (b.sortDate ?? b.date ?? "").localeCompare(a.sortDate ?? a.date ?? ""));

export const callRegisteredSongs: SetlistTrack[] = Array.from(
  new Map(
    getLiveSetlistsByLatest()
      .flatMap((setlist) => setlist.tracks)
      .filter((track) => track.kind !== "note")
      .map((track) => [track.title, track])
  ).values()
);
