delete from call_events
where song_title = '盛れ!ミ・アモーレ'
  and video_id = 'G36amiUCkXU';

insert into call_events
  (id, song_title, video_id, time, phrase, note, created_by, updated_at)
values
  ('m01', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 3.7, '盛れ！', '高速編集', 'local-seed', current_timestamp),
  ('m02', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 7.5, '盛れ！', '高速編集', 'local-seed', current_timestamp),
  ('m03', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 9.6, '盛れ！', '高速編集', 'local-seed', current_timestamp),
  ('m04', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 11.5, '盛れ！', '高速編集', 'local-seed', current_timestamp),
  ('m05', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 22.6, 'オイ！×4', '高速編集', 'local-seed', current_timestamp),
  ('m06', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 24.4, 'オイ！×4', '高速編集', 'local-seed', current_timestamp),
  ('m07', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 37.5, 'ゆめちゃん', '高速編集', 'local-seed', current_timestamp),
  ('m08', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 41.0, 'みふちゃん', '高速編集', 'local-seed', current_timestamp),
  ('m09', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 43.1, 'るるちゃん', '高速編集', 'local-seed', current_timestamp),
  ('m10', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 44.7, 'るるちゃん', '高速編集', 'local-seed', current_timestamp),
  ('m11', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 47.9, 'きさき', '高速編集', 'local-seed', current_timestamp),
  ('m12', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 66.3, 'アモーレ ミ・アモーレ！', '高速編集', 'local-seed', current_timestamp),
  ('m13', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 73.2, 'オイ！×4', '高速編集', 'local-seed', current_timestamp),
  ('m14', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 75.0, 'オイ！×4', '高速編集', 'local-seed', current_timestamp),
  ('m15', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 80.2, 'アモーレ ミ・アモーレ！', '高速編集', 'local-seed', current_timestamp),
  ('m16', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 87.1, 'オイ！×4', '高速編集', 'local-seed', current_timestamp),
  ('m17', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 88.8, 'オイ！×4', '高速編集', 'local-seed', current_timestamp),
  ('m18', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 96.0, '盛れ！', '高速編集', 'local-seed', current_timestamp),
  ('m19', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 100.2, 'りあい', '高速編集', 'local-seed', current_timestamp),
  ('m20', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 103.6, 'きさき', '高速編集', 'local-seed', current_timestamp),
  ('m21', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 105.0, 'れいれい', '高速編集', 'local-seed', current_timestamp),
  ('m22', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 107.0, 'れいれい', '高速編集', 'local-seed', current_timestamp),
  ('m23', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 110.2, 'るるちゃん', '高速編集', 'local-seed', current_timestamp),
  ('m24', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 128.9, 'アモーレ ミ・アモーレ！', '高速編集', 'local-seed', current_timestamp),
  ('m25', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 135.9, 'オイ！×4', '高速編集', 'local-seed', current_timestamp),
  ('m26', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 137.7, 'オイ！×4', '高速編集', 'local-seed', current_timestamp),
  ('m27', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 142.7, 'アモーレ ミ・アモーレ！', '高速編集', 'local-seed', current_timestamp),
  ('m28', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 149.8, 'オイ！×4', '高速編集', 'local-seed', current_timestamp),
  ('m29', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 151.6, 'オイ！×4', '高速編集', 'local-seed', current_timestamp),
  ('m30', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 158.4, '盛れ！', '高速編集', 'local-seed', current_timestamp),
  ('m31', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 161.0, 'オイ！', '高速編集', 'local-seed', current_timestamp),
  ('m32', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 161.8, 'オイ！', '高速編集', 'local-seed', current_timestamp),
  ('m33', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 162.5, 'オイ！', '高速編集', 'local-seed', current_timestamp),
  ('m34', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 163.3, 'オイ！', '高速編集', 'local-seed', current_timestamp),
  ('m35', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 164.5, 'オイ！', '高速編集', 'local-seed', current_timestamp),
  ('m36', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 165.2, 'オイ！', '高速編集', 'local-seed', current_timestamp),
  ('m37', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 166.1, 'オイ！', '高速編集', 'local-seed', current_timestamp),
  ('m38', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 167.1, '盛れ！', '高速編集', 'local-seed', current_timestamp),
  ('m39', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 168.8, '盛れ！', '高速編集', 'local-seed', current_timestamp),
  ('m40', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 170.6, '盛れ！', '高速編集', 'local-seed', current_timestamp),
  ('m41', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 172.3, '盛れ！', '高速編集', 'local-seed', current_timestamp),
  ('m42', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 192.1, 'アモーレ ミ・アモーレ！', '高速編集', 'local-seed', current_timestamp),
  ('m43', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 198.5, 'オイ！×4', '高速編集', 'local-seed', current_timestamp),
  ('m44', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 200.7, 'オイ！×4', '高速編集', 'local-seed', current_timestamp),
  ('m45', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 207.1, '盛れ！', '高速編集', 'local-seed', current_timestamp),
  ('m46', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 208.1, '盛れ！', '高速編集', 'local-seed', current_timestamp),
  ('m47', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 208.8, '盛れ！', '高速編集', 'local-seed', current_timestamp),
  ('m48', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 209.3, '盛れ！', '高速編集', 'local-seed', current_timestamp),
  ('m49', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 209.7, '盛れ！', '高速編集', 'local-seed', current_timestamp),
  ('m50', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 210.5, 'ライライライララライララーイ', '高速編集', 'local-seed', current_timestamp),
  ('m51', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 213.6, 'ライライライララライララーイ', '高速編集', 'local-seed', current_timestamp),
  ('m52', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 217.7, 'M・O・R・E！', '高速編集', 'local-seed', current_timestamp),
  ('m53', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 219.4, 'M・O・R・E！', '高速編集', 'local-seed', current_timestamp),
  ('m54', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 221.2, 'オー！フゥ！', '高速編集', 'local-seed', current_timestamp),
  ('m55', '盛れ!ミ・アモーレ', 'G36amiUCkXU', 225.4, '盛れ！', '高速編集', 'local-seed', current_timestamp);
